# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none
#- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@1
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/s/target/'
    Contents: '*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kirangowda9684 / firstrepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      # version
      Write-Host $pomXml.project.version
      $version=$pomXml.project.version
      Write-Host "##vso[task.setvariable variable=version]$version"
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'kirangowda9684 (1)'
    repositoryName: 'kirangowda9684/maven-web-application'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: '($version)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'